apiVersion: apps/v1
kind: Deployment
metadata:
  name: spanner-crud-status-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spanner-crud-status-pod
  template:
    metadata:
      labels:
        app: spanner-crud-status-pod
    spec:
      containers:
        - image: gcr.io/pnr-order-poc/spanner-crud-status:latest
          name: spanner-crud-status
