apiVersion: v1
kind: Service
metadata:
  name: spanner-crud-status
  labels:
    app: spanner-crud-status
spec:
  ports:
    - protocol: TCP
      port: 81
      targetPort: 8081
  selector:
    app: spanner-crud-status-poda
  type: LoadBalancer