apiVersion: v1
kind: Service
metadata:
  name: spanner-crud-status-service
  labels:
    app: spanner-crud-status-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: spanner-crud-status-pod
  type: LoadBalancer
